location ~ \.py$ {
    tree_sitter_filter on;

    # language_name must match the main function name
    # example: tree_sitter_python
    tree_sitter_language_name python;

    tree_sitter_parser_path /parsers/python/parser.so;

    tree_sitter_highlights_path /parsers/python/queries/highlights.scm;

    tree_sitter_css_style ".comment{color:gray;} .function{color:green;}";

    # for raw=1
    # override the default mime type "application/octet-stream"
    default_type "text/x-py; charset=utf-8";
}

location ~ \.(cpp|cc|c\+\+|cxx|hpp|h\+\+|hh|hxx)$ {
    tree_sitter_filter on;
    tree_sitter_language_name cpp;
    tree_sitter_parser_path /parsers/cpp/parser.so;
    tree_sitter_highlights_path /parsers/cpp/queries/highlights.scm;
    default_type "text/x-cpp; charset=utf-8";
}
